480p:
    exec_dir: "$HOME/test/"
    data_dirs: "$HOME/test/"
    execs:
        - gears:
          - args: 'NO_ARGS'
        - instancing:
          - args: 'NO_ARGS'
        - pbrtexture:
          - args: 'NO_ARGS'
        - tessellation:
          - args: 'NO_ARGS'

QHD:
    exec_dir: "$HOME/test/"
    data_dirs: "$HOME/test/"
    execs:
        - gears:
          - args: 'NO_ARGS'
        - render_passes:
          - args: 'NO_ARGS'
        - render_passes_lod0:
          - args: 'NO_ARGS'
        - instancing:
          - args: 'NO_ARGS'
        - pbrtexture:
          - args: 'NO_ARGS'
        - pipelines:
          - args: 'NO_ARGS'
        - tessellation:
          - args: 'NO_ARGS'
        - geometryshader:
          - args: 'NO_ARGS'

4K-UHD:
    exec_dir: "$HOME/test/"
    data_dirs: "$HOME/test/"
    execs:
        - gears:
          - args: 'NO_ARGS'
        - render_passes:
          - args: 'NO_ARGS'
        - instancing:
          - args: 'NO_ARGS'
        - pbrtexture:
          - args: 'NO_ARGS'

artifact-merged:
    exec_dir: "$HOME/test/"
    data_dirs: "$HOME/test/"
    execs:
        - render_passes_2k:
          #- args: 'NO_ARGS'
          - args: 'all1'

artifact-separate:
    exec_dir: "$HOME/test/"
    data_dirs: "$HOME/test/"
    execs:
        - render_passes_2k:
          - args: 'NO_ARGS'
        - klt_tracker:
          - args: "cam0"
        - vpi_sample_03_harris_corners:
          - args: "cuda__home_pan251_cam0_img_0126_png"
        - vpi_sample_11_fisheye:
          - args: "_c_10_7__s_22___cam0_img_0000_png"
        - vpi_sample_12_optflow_lk_refined:
          - args: "cuda__home_pan251_cam0_10_img__4d_png_5_frames_png"
        - render_passes_2k_lod0:
          - args: 'NO_ARGS'

crisp:
    exec_dir: "$HOME/test/"
    data_dirs: "$HOME/test/"
    execs:
        - render_passes_2k:
          - args: 'NO_ARGS'
        - render_passes_2k_lod0:
          - args: 'NO_ARGS'
        - gears_2k:
          - args: 'NO_ARGS'
        - instancing_2k:
          - args: 'NO_ARGS'
        - pbrtexture_2k:
          - args: 'NO_ARGS'
        - tessellation_2k:
          - args: 'NO_ARGS'
        - klt_tracker:
          - args: "cam0"
        - vpi_sample_03_harris_corners:
          - args: "cuda__home_pan251_cam0_img_0126_png"
        - vpi_sample_11_fisheye:
          - args: "_c_10_7__s_22___cam0_img_0000_png"
        - vpi_sample_12_optflow_lk_refined:
          - args: "cuda__home_pan251_cam0_10_img__4d_png_5_frames_png"

pipeline:
    exec_dir: "$HOME/test/"
    data_dirs: "$HOME/test/"
    execs:
        - minitrace:
          - args: 'NO_ARGS'
